=== Moataz-Elmesmary/ITI-Business-Intelligence-Development/XML/Day 1/Lab 1 Answers/family.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT family (grandfather)>
<!ELEMENT grandfather (father, uncle+, aunt)>
<!ELEMENT father (mother, daughter, son)>
<!ATTLIST father job CDATA #REQUIRED>
<!ELEMENT mother EMPTY>
<!ELEMENT daughter EMPTY>

<!ATTLIST daughter age CDATA #REQUIRED job CDATA #REQUIRED>
<!ELEMENT son EMPTY>
<!ATTLIST son age CDATA #REQUIRED sport CDATA #REQUIRED>
<!ELEMENT uncle EMPTY>
<!ELEMENT aunt EMPTY>
<!ATTLIST aunt sons CDATA #REQUIRED>

=== Moataz-Elmesmary/ITI-Business-Intelligence-Development/XML/Day 1/Lab 1 Answers/XMLfam.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--  <!DOCTYPE family SYSTEM "family.dtd">  -->
<family>
    <grandfather>
        <father job="Teacher">
            <mother>
            </mother>
            <daughter age="20" job="Doctor"></daughter>
            <son age="20" sport="Football"></son>
        </father>
        <uncle>
		</uncle>
		<uncle>
        </uncle>
        <aunt sons="2"></aunt>
    </grandfather>
</family>
